### ISSUE TITLE
Redirect all "non-localized" routes to the corresponding "localized"

### ISSUE THREAD

**Issue by enstain** [cariboufute/locale-route#5]
## Detailed description

When I define some LocaleRoute, for e.g. for home page and visit it as usual at "site.name/", I've got an error about "not defined" route. So, I have to visit "site.name/locale" to see a working page

## Context

It's breaking because users usually visit "site.name/" and expect working page here

## Possible implementation

Package laravel-localization provides middleware to implement such functional: https://github.com/mcamara/laravel-localization#middleware

**Comment by cariboufute** [comment]
I really don't like this feature of laravel-localization. I prefer to not implement this feature, because the package would become too opiniated on URL possibilities and could mess up with non locale routes.

Please check the locale-route-example route file. All you need to add is a normal GET route with a redirection to fallback_locale, like this.

``` php
Route::get('/', function () {
    return redirect('/' . Config::get('app.fallback_locale'));
});
```

If you want to remove all locales in URLs (which I don't recommend for readability of URL locale), just turn the `'add_locale_to_url'` to _false_.
